OBJS=sumer.pdf

PLIKI=sumer.tex

# wprowadzenie.tex tabliczki.tex interfejs.tex plyta.tex implementacja.tex

default: $(PLIKI)
	pdflatex sumer.tex
	pdflatex sumer.tex
#	mv sumer.pdf ../SumLib.pdf

clear:
	rm *.log *.aux *.toc

clean:
	rm *.pdf
#	rm ../SumLib.*.pdf